//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Category
    {
        public
            tbl_Category()
        {
            this.tbl_Url = new HashSet<tbl_Url>();
        }
        public int CategoryId { get; set; }
        
        public string CategoryName { get; set; }
        
        public string CategoryDesc { get; set; }

        public virtual ICollection<tbl_Url> tbl_Url { get; set; }
    }
}
